services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    expose:
      - "5678"
    environment:
      - N8N_HOST=n8n.yasasvi.site
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=https://n8n.yasasvi.site
    restart: always
    networks:
      - deploy_net

networks:
  deploy_net:
    external: true
