services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    expose:
      - "5678"
    restart: always
    networks:
      - deploy_net

networks:
  deploy_net:
    external: true
